# Generated by Django 5.2.4 on 2025-09-04 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lettres", "0002_lettre_created_by"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="response",
            unique_together={("lettre", "destination")},
        ),
    ]
