# Generated by Django 5.2.4 on 2025-09-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lettres", "0003_alter_response_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente d'approbation"),
                    ("accepted", "Acceptée"),
                    ("revision_requested", "Révision demandée"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="revision_comments",
            field=models.TextField(blank=True),
        ),
    ]
