# Generated by Django 5.2.4 on 2025-09-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lettres", "0004_response_approval_status_response_revision_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profiles/",
                verbose_name="Photo de profil",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente "),
                    ("accepted", "Acceptée"),
                    ("revision_requested", "Révision demandée"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
